import { z } from 'zod';

export const submitSchema = z.object({
  entityType: z.enum(['person', 'shop', 'club']),
  displayName: z.string().min(2),
  email: z.string().email(),
  city_id: z.number(),
  country_id: z.number(),
  bio: z.string().max(280),
  ageBand: z.string().optional(),
  parentName: z.string().optional(),
  parentEmail: z.string().email().optional(),
  relationship: z.string().optional(),
  addressLine: z.string().optional(),
  postalCode: z.string().optional(),
  hours: z.string().optional(),
  contactName: z.string().optional(),
  authorizedRep: z.boolean().optional(),
  clubMeetingInfo: z.string().optional(),
  clubVenuePublic: z.boolean().optional(),
  venueAddressLine: z.string().optional(),
  venuePostalCode: z.string().optional(),
  instagram: z.string().optional(),
  youtube: z.string().optional(),
  discord: z.string().optional(),
  website: z.string().optional(),
  consentPrivacy: z.boolean(),
  consentTerms: z.boolean(),
  consentPublic: z.boolean(),
  honeypot: z.string().optional(),
});
