-- =============================================================================
-- Drop overly-permissive reports INSERT policy
-- =============================================================================
-- The "Anyone can submit a report" INSERT policy used WITH CHECK (true), which
-- the Supabase linter flags as bypassing RLS.
--
-- It's safe to drop because:
--   1. All report inserts go through app/api/report/route.ts using the
--      service_role client, which bypasses RLS entirely.
--   2. The anon role is already revoked on public.reports
--      (see schema.sql: "revoke all on public.reports from anon").
--   3. No authenticated grant exists on the table, so dropping this policy
--      does not change the capability of any client-side role.
-- =============================================================================

-- DROP POLICY IF EXISTS "Anyone can submit a report" ON reports;
