-- Yo-yo Clubs (bulk insert; generated from CSVs 2026-04-23)
-- NOTE: Dummy emails used; update as needed. Lat/lng are approximate city centers.
insert into entries (
  display_name, city, region, country, lat, lng, exact_lat, exact_lng, address_line, postal_code, entity_type, is_visible, email, age_band, bio, socials, hours, club_meeting_info, club_venue_public
) values
('AllYoYo (Phoenix)', 'Phoenix', 'AZ', 'USA', 33.4484, -112.0740, 33.4484, -112.0740, NULL, NULL, 'club', true, 'club+allyoyo-phoenix@example.com', NULL, 'Free weekly class, active as recently as 2022+. Distinct from Chandler (east metro). Also a performance troupe.', '{"website": "allyoyo.com", "instagram": "@allyoyo"}', NULL, 'Weekly class, see IG for schedule', true),
('West Side Throwers', 'El Mirage', 'AZ', 'USA', 33.6131, -112.3246, 33.6131, -112.3246, NULL, NULL, 'club', true, 'club+westside-throwers@example.com', NULL, 'West Phoenix — geographically distinct from Chandler and AllYoYo.', '{"instagram": "@devinfilmstuff", "email": "devinmschulz@gmail.com"}', NULL, 'Contact Devin for details', true),
('Marietta Yo-Yo Club', 'Marietta', 'GA', 'USA', 33.9526, -84.5499, 33.9526, -84.5499, NULL, NULL, 'club', true, 'club+marietta@example.com', NULL, 'NW Atlanta metro. Distinct from (Metro) Atlanta Yo-Yo Club which meets in Alpharetta.', '{"instagram": "@ggmarkd", "email": "mdiehr@gmail.com"}', NULL, 'Contact Mark for details', true),
('Alternate Worlds Skill Toys Club', 'Hunt Valley', 'MD', 'USA', 39.4987, -76.6464, 39.4987, -76.6464, NULL, NULL, 'club', true, 'club+alternateworlds@example.com', NULL, 'Game store hosted; ~70 mi N of Dumfries.', '{"website": "https://alternateworlds.com"}', NULL, 'Alternate Worlds game store', true),
('NC Yo-Yo Chuckers', 'Morganton-Statesville', 'NC', 'USA', 35.7454, -81.6848, 35.7454, -81.6848, NULL, NULL, 'club', true, 'club+nc-chuckers@example.com', NULL, 'Western NC foothills. Distinct from Triad Area Throwers.', '{"instagram": "@bigbs_domain1985", "email": "bigbs_domain@yahoo.com"}', NULL, 'Contact Brandon for details', true),
('The Cleveland Yo-Yo Club', 'Westlake', 'OH', 'USA', 41.4553, -81.9179, 41.4553, -81.9179, NULL, NULL, 'club', true, 'club+cleveyoyo@example.com', NULL, 'Est. 2008, non-profit, 765 FB likes. Surprising omission — major OH club. @cleveyoyo on X.', '{"twitter": "@cleveyoyo"}', NULL, '2nd Sat monthly 2-4pm at Learning Express Westlake', true),
('Steel City Throwers', 'Pittsburgh', 'PA', 'USA', 40.4406, -79.9959, 40.4406, -79.9959, NULL, NULL, 'club', true, 'club+steelcitythrowers@example.com', NULL, 'Annual Steel City Throwers contest (hosts PA State 2026). Active forum thread Jun 2025.', '{"instagram": "@steelcitythrowers", "linktree": "linktr.ee/Steelcitythrowers"}', NULL, 'See IG for meetings', true),
('Alamo Yoyo Club', 'San Antonio', 'TX', 'USA', 29.4241, -98.4936, 29.4241, -98.4936, NULL, NULL, 'club', true, 'club+alamoyoyo@example.com', NULL, 'Yo-yo AND juggling AND spintop (2x world champ Jorge Alcoz). Confirmed active 2024.', '{"instagram": "@alamoyoyoclub"}', NULL, 'Last Sun of month 2-5pm at Phil Hardberger Park', true),
('Tri-Cities Yo-Yo Club', 'Kennewick', 'WA', 'USA', 46.2112, -119.1372, 46.2112, -119.1372, NULL, NULL, 'club', true, 'club+tricities@example.com', NULL, 'Eastern WA. Distinct from T.O.P.S. (Puget Sound).', '{"facebook": "group"}', NULL, 'Contact via Facebook group', true),
('San Diego Yoyo Club', 'San Diego', 'CA', 'USA', 32.7157, -117.1611, 32.7157, -117.1611, NULL, NULL, 'club', true, 'club+sandiego@example.com', NULL, 'San Diego Classic 2025 contest exists. Wiki entry may be stale — verify current meetings.', '{"website": "https://yoyo.fandom.com/wiki/San_Diego_Yoyo_Club"}', NULL, '2nd & 4th Sat 3-6pm, Balboa Park', true),
('Orlando Yo-Yo Club', 'Orlando', 'FL', 'USA', 28.5383, -81.3792, 28.5383, -81.3792, NULL, NULL, 'club', true, 'club+orlando@example.com', NULL, 'Possibly overlaps with Central Florida Yo-Yo Club (on map). Could be same group or separate.', '{"facebook": "page+group"}', NULL, 'Contact via Facebook', true),
('YoYoNashville', 'Nashville', 'TN', 'USA', 36.1627, -86.7816, 36.1627, -86.7816, NULL, NULL, 'club', true, 'club+yoyonashville@example.com', NULL, 'Very likely same as Nashville Yo-Yo Club on map. Treat as duplicate unless verified separate.', '{}', NULL, 'Contact local players for info', true),
('Toronto Yo-Yo Club', 'Toronto', 'ON', 'Canada', 43.6532, -79.3832, 43.6532, -79.3832, NULL, NULL, 'club', true, 'club+toronto@example.com', NULL, 'Long-running Canadian club. Canada is an official IYYF member nation.', '{"facebook": "group"}', NULL, 'See Facebook group', true),
('Calgary Yoyo Club', 'Calgary', 'AB', 'Canada', 51.0447, -114.0719, 51.0447, -114.0719, NULL, NULL, 'club', true, 'club+calgary@example.com', NULL, 'Active IG, posts monthly meetups.', '{"instagram": "@yoyo.calgary"}', NULL, 'See Instagram for schedule', true),
('Ottawa Yoyo Club', 'Ottawa', 'ON', 'Canada', 45.4215, -75.6997, 45.4215, -75.6997, NULL, NULL, 'club', true, 'club+ottawa@example.com', NULL, 'Active IG presence.', '{"instagram": "@ottawa_yoyo_club"}', NULL, 'See Instagram for schedule', true);
-- Yo-yo Storefronts US: Bulk insert for map entries
-- NOTE: Replace placeholder emails and age_band as needed



insert into entries (
  display_name, city, region, country, lat, lng, exact_lat, exact_lng, address_line, postal_code, entity_type, is_visible, email, age_band, bio, socials, hours
) values
('YoYoExpert', 'Easthampton', 'MA', 'USA', 42.2668, -72.6687, 42.2668, -72.6687, '116 Pleasant St, Suite 201', '01027', 'shop', true, 'store+yoyoexpert@example.com', NULL, 'Eastworks Building. Walk-in store + warehouse. Owner Andre Boulay. Hours Mon-Fri 10a-5p ET.', '{"website": "https://yoyoexpert.com", "phone": "(413) 551-9696"}', 'Mon-Fri 10a-5p ET'),
('YoYoFactory', 'Chandler', 'AZ', 'USA', 33.3062, -111.8413, 33.3062, -111.8413, '155 E Chilton Dr, Ste 101', '85225', 'shop', true, 'store+yoyofactory@example.com', NULL, 'Manufacturer HQ with retail storefront. Mon-Fri 9a-5p.', '{"website": "https://yoyofactory.com", "phone": "(480) 753-3444"}', 'Mon-Fri 9a-5p'),
('National Yo-Yo Museum (Bird in Hand)', 'Chico', 'CA', 'USA', 39.7289, -121.8375, 39.7289, -121.8375, '320 Broadway St', '95928', 'shop', true, 'store+nationalyoyo@example.com', NULL, 'Museum inside Bird in Hand toy/gift shop; yo-yos sold on-site. Free admission. Saturday lessons noon-2p. Home of 256lb Big-Yo.', '{"website": "https://nationalyoyo.org", "phone": "(530) 893-0545"}', 'Sat noon-2p lessons'),
('YoYoSam', 'Fairview', 'PA', 'USA', 42.0242, -80.2551, 42.0242, -80.2551, 'Fairview area', '16415', 'shop', true, 'store+yoyosam@example.com', NULL, 'Physical store exists but appointment-only since COVID. Call ahead. Brandon''s ambassador code: Captnyoyos.', '{"website": "https://yoyosam.com"}', NULL),
('YoYoLoco', 'Breckenridge', 'CO', 'USA', 39.4797, -106.0419, 39.4797, -106.0419, '306 S Main St', '80424', 'shop', false, 'store+yoyoloco@example.com', NULL, 'Yelp lists as CLOSED but website active. Owner Mark Levey. May be online-only. Confirm before publishing.', '{"website": "https://yoyoloco.com", "phone": "(970) 409-3101"}', NULL),
('Infinite Illusions / YoYoGuy', 'Tallahassee', 'FL', 'USA', 30.4713, -84.2807, 30.4713, -84.2807, '1205 Commercial Park Dr', '32303', 'shop', false, 'store+yoyoguy@example.com', NULL, 'Warehouse/office, not walk-in retail. Yelp shows closed. Business still operates online. Call first.', '{"website": "https://yoyoguy.com", "phone": "(850) 385-6463"}', NULL),
('Duncan Toys Company', 'Middlefield', 'OH', 'USA', 41.4567, -81.0712, 41.4567, -81.0712, '15981 Valplast Rd', '44062', 'shop', false, 'store+duncan@example.com', NULL, 'Founded 1929. Became independent company in Oct 2024 after spinning off from Flambeau. No public retail; factory/offices only.', '{"website": "https://duncantoys.com", "phone": "(440) 632-1631"}', NULL),
('Yomega Corporation', 'Seekonk', 'MA', 'USA', 41.7805, -71.2965, 41.7805, -71.2965, '1950 Fall River Ave', '02771', 'shop', false, 'store+yomega@example.com', NULL, 'Founded 1983. Family-owned. No public retail; offices/warehouse.', '{"website": "https://yomega.com", "phone": "(508) 557-0030"}', NULL),
('One Drop YoYos', 'Eugene', 'OR', 'USA', 44.0520, -123.1187, 44.0520, -123.1187, '663 Taylor St', '97402', 'shop', false, 'store+onedrop@example.com', NULL, 'Premium US-made yo-yos since 2007. In-house machine shop. No public retail - workshop only.', '{"website": "https://onedropyoyos.com"}', NULL),
('The Yo-Yo Shop', 'Kissimmee', 'FL', 'USA', 28.2920, -81.4076, 28.2920, -81.4076, '3819 Shoreside Dr (mailing only)', '34746', 'shop', false, 'store+yoyoshop@example.com', NULL, 'Online retailer only. Owner Brandon Jackson (ex-Duncan). No walk-in storefront per their own contact page. Orlando/Kissimmee area.', '{"website": "https://yo-yoshop.com"}', NULL),
('Yo-Yo Store REWIND USA', 'Online', NULL, 'USA', 39.8283, -98.5795, 39.8283, -98.5795, 'Online only', NULL, 'shop', false, 'store+rewindusa@example.com', NULL, 'US arm of Japan''s REWIND. Online only; exact US warehouse not public. Consider hiding from map or geocoding later.', '{"website": "https://usa.yoyostorerewind.com"}', NULL),
('Recess Intl', 'Online', NULL, 'USA', 39.8283, -98.5795, 39.8283, -98.5795, 'Online only', NULL, 'shop', false, 'store+recessintl@example.com', NULL, 'Small boutique brand founded 2015 by Tyler Severance. No public HQ address. Sold via partner retailers.', '{"website": "https://recessintl.com"}', NULL),
('Kendama USA', 'Online', 'WY', 'USA', 39.8283, -98.5795, 39.8283, -98.5795, 'Online only', NULL, 'shop', false, 'store+kendamausa@example.com', NULL, 'Remote/distributed team. Admin HQ Wyoming, legal reg Georgia. No public retail per their own FAQ. Major kendama brand since 2006.', '{"website": "https://kendamausa.com"}', NULL),
('Caribou Lodge (CLYW)', 'Edmonton', 'AB', 'Canada', 53.5461, -113.4938, 53.5461, -113.4938, 'Online only', NULL, 'shop', false, 'store+clyw@example.com', NULL, 'Canadian premium yo-yo brand founded 2006 by Chris Mikulin. Outside US scope but included as major North American manufacturer. No public retail.', '{"website": "https://cariboulodge.store"}', NULL);


insert into entries (
  display_name, city, region, country, lat, lng, exact_lat, exact_lng, address_line, postal_code, entity_type, is_visible, email, age_band, bio, socials, hours, club_meeting_info, club_venue_public
) values
('AllYoYo (Phoenix)', 'Phoenix', 'AZ', 'USA', 33.4484, -112.0740, 33.4484, -112.0740, NULL, NULL, 'club', true, 'club+allyoyo-phoenix@example.com', NULL, 'Free weekly class, active as recently as 2022+. Distinct from Chandler (east metro). Also a performance troupe.', '{"website": "allyoyo.com", "instagram": "@allyoyo"}', NULL, 'Weekly class, see IG for schedule', true),
('West Side Throwers', 'El Mirage', 'AZ', 'USA', 33.6131, -112.3246, 33.6131, -112.3246, NULL, NULL, 'club', true, 'club+westside-throwers@example.com', NULL, 'West Phoenix — geographically distinct from Chandler and AllYoYo.', '{"instagram": "@devinfilmstuff", "email": "devinmschulz@gmail.com"}', NULL, 'Contact Devin for details', true),
('Marietta Yo-Yo Club', 'Marietta', 'GA', 'USA', 33.9526, -84.5499, 33.9526, -84.5499, NULL, NULL, 'club', true, 'club+marietta@example.com', NULL, 'NW Atlanta metro. Distinct from (Metro) Atlanta Yo-Yo Club which meets in Alpharetta.', '{"instagram": "@ggmarkd", "email": "mdiehr@gmail.com"}', NULL, 'Contact Mark for details', true),
('Alternate Worlds Skill Toys Club', 'Hunt Valley', 'MD', 'USA', 39.4987, -76.6464, 39.4987, -76.6464, NULL, NULL, 'club', true, 'club+alternateworlds@example.com', NULL, 'Game store hosted; ~70 mi N of Dumfries.', '{"website": "https://alternateworlds.com"}', NULL, 'Alternate Worlds game store', true),
('NC Yo-Yo Chuckers', 'Morganton-Statesville', 'NC', 'USA', 35.7454, -81.6848, 35.7454, -81.6848, NULL, NULL, 'club', true, 'club+nc-chuckers@example.com', NULL, 'Western NC foothills. Distinct from Triad Area Throwers.', '{"instagram": "@bigbs_domain1985", "email": "bigbs_domain@yahoo.com"}', NULL, 'Contact Brandon for details', true),
('The Cleveland Yo-Yo Club', 'Westlake', 'OH', 'USA', 41.4553, -81.9179, 41.4553, -81.9179, NULL, NULL, 'club', true, 'club+cleveyoyo@example.com', NULL, 'Est. 2008, non-profit, 765 FB likes. Surprising omission — major OH club. @cleveyoyo on X.', '{"twitter": "@cleveyoyo"}', NULL, '2nd Sat monthly 2-4pm at Learning Express Westlake', true),
('Steel City Throwers', 'Pittsburgh', 'PA', 'USA', 40.4406, -79.9959, 40.4406, -79.9959, NULL, NULL, 'club', true, 'club+steelcitythrowers@example.com', NULL, 'Annual Steel City Throwers contest (hosts PA State 2026). Active forum thread Jun 2025.', '{"instagram": "@steelcitythrowers", "linktree": "linktr.ee/Steelcitythrowers"}', NULL, 'See IG for meetings', true),
('Alamo Yoyo Club', 'San Antonio', 'TX', 'USA', 29.4241, -98.4936, 29.4241, -98.4936, NULL, NULL, 'club', true, 'club+alamoyoyo@example.com', NULL, 'Yo-yo AND juggling AND spintop (2x world champ Jorge Alcoz). Confirmed active 2024.', '{"instagram": "@alamoyoyoclub"}', NULL, 'Last Sun of month 2-5pm at Phil Hardberger Park', true),
('Tri-Cities Yo-Yo Club', 'Kennewick', 'WA', 'USA', 46.2112, -119.1372, 46.2112, -119.1372, NULL, NULL, 'club', true, 'club+tricities@example.com', NULL, 'Eastern WA. Distinct from T.O.P.S. (Puget Sound).', '{"facebook": "group"}', NULL, 'Contact via Facebook group', true),
('San Diego Yoyo Club', 'San Diego', 'CA', 'USA', 32.7157, -117.1611, 32.7157, -117.1611, NULL, NULL, 'club', true, 'club+sandiego@example.com', NULL, 'San Diego Classic 2025 contest exists. Wiki entry may be stale — verify current meetings.', '{"website": "https://yoyo.fandom.com/wiki/San_Diego_Yoyo_Club"}', NULL, '2nd & 4th Sat 3-6pm, Balboa Park', true),
('Orlando Yo-Yo Club', 'Orlando', 'FL', 'USA', 28.5383, -81.3792, 28.5383, -81.3792, NULL, NULL, 'club', true, 'club+orlando@example.com', NULL, 'Possibly overlaps with Central Florida Yo-Yo Club (on map). Could be same group or separate.', '{"facebook": "page+group"}', NULL, 'Contact via Facebook', true),
('YoYoNashville', 'Nashville', 'TN', 'USA', 36.1627, -86.7816, 36.1627, -86.7816, NULL, NULL, 'club', true, 'club+yoyonashville@example.com', NULL, 'Very likely same as Nashville Yo-Yo Club on map. Treat as duplicate unless verified separate.', '{}', NULL, 'Contact local players for info', true),
('Toronto Yo-Yo Club', 'Toronto', 'ON', 'Canada', 43.6532, -79.3832, 43.6532, -79.3832, NULL, NULL, 'club', true, 'club+toronto@example.com', NULL, 'Long-running Canadian club. Canada is an official IYYF member nation.', '{"facebook": "group"}', NULL, 'See Facebook group', true),
('Calgary Yoyo Club', 'Calgary', 'AB', 'Canada', 51.0447, -114.0719, 51.0447, -114.0719, NULL, NULL, 'club', true, 'club+calgary@example.com', NULL, 'Active IG, posts monthly meetups.', '{"instagram": "@yoyo.calgary"}', NULL, 'See Instagram for schedule', true),
('Ottawa Yoyo Club', 'Ottawa', 'ON', 'Canada', 45.4215, -75.6997, 45.4215, -75.6997, NULL, NULL, 'club', true, 'club+ottawa@example.com', NULL, 'Active IG presence.', '{"instagram": "@ottawa_yoyo_club"}', NULL, 'See Instagram for schedule', true);

-- Note: Some entries are set is_visible=false due to low confidence or missing coordinates. Review before enabling.
-- For online-only stores without a city/lat/lng, consider hiding or geocoding later.
